# Generated by Django 5.1 on 2024-08-23 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="age",
            new_name="crowd_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="images/"
            ),
            preserve_default=False,
        ),
    ]
