# Generated by Django 5.1 on 2024-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_age_user_crowd_count_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="crowd_count",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
