# Generated by Django 5.1 on 2024-08-23 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_user_crowd_count_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
