# Generated by Django 5.1 on 2024-08-25 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_user_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alert",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
